[project]
name = "tda-project"
version = "0.1.0"
dependencies = [
    "numpy==1.26.4",
    "biopython==1.85",
    "matplotlib==3.10.3",
    "scipy==1.15.3",
    "gudhi==3.11.0",
    "PyQt5==5.15.11",
    "POT==0.9.5"
]